language: java
script: mvn -q clean install
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
# whitelist
branches:
  only:
    - travis-sonatype-snapshot-publish-org-shamdata

notifications:
  email:
    - cucumber-test@tomd.cc

